# host name are hardcoded for now. Future overrride should
# be stored/referenced inside customers Gitops repo.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewhatever-com/zippy-k11
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: 
    chart: kubewhatever-com/zippy
    targetRevision: None
    helm:
      values: |-
        kubewhatever-com/zippy:
          image:
            repository: /kubewhatever-com/zippy
          ingress:
            className: nginx
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/service-upstream: "true"
              cert-manager.io/issuer: letsencrypt-prod
            hosts:
              - host: kubewhatever-com/zippy-k11.gitopsmagic.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kubewhatever-com/zippy-tls
                hosts:
                  - kubewhatever-com/zippy-k11.gitopsmagic.com
  destination:
    name: k11
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
